### ISSUE TITLE
AppKey

### ISSUE THREAD

**Issue by siarheiskalaban** [NeoSmartpen/NcodeSDK#1]
Hello,
Where can I obtain application key, register and pay for tickets?

Thanx,
Siarhei Skalaban

**Comment by tentarc** [comment]
Sorry for the delay in your reply.
Currently our company is setting code usage policy. Coming soon.
If you want to use it as soon as possible, please send us the necessary information.
As soon as the policy is established, we will prepare to start development immediately.

Account ID (required)
Password (required)
Company name (required)
Extra information for account (if you are going to create multiple accounts)
Application names (required)
Extra information (if you are going to create multiple applications)

Please send the above information to hrhwang@neolab.net if you want.
We will contact you again once we have verified the details.

**Comment by smartrxhub** [comment]
Hello,

We are looking for setup appkey and ticket -price information , Please advise your company has define policy for pattern generation .

Thanks
Praful
SmartRxHub

**Comment by hrhwang** [comment]
We will explain our pricing policy.
Please leave an email address.

**Comment by smartrxhub** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hi 
Praful@smartrxhub.ca . Please send me email.
Thanks 


Sent from Yahoo Mail for iPhone


On Sunday, May 21, 2017, 10:17 PM, hrhwang <notifications@github.com> wrote:


We will explain our pricing policy.
Please leave an email address.

**Comment by smartrxhub** [comment]
Hello,

please email to praful@smartrxhub.ca

thanks

**Comment by emeyke** [comment]
We are also interested in this information 
Evgeniy@meyke.info

**Comment by hrhwang** [comment]
This is the NCode pricing policy.


Ncode SDK
Standard Package
Benefits	License Fee
Server maintainance	Up to xxx GB of server storage ​​(​To be decided)	
5,000 USD per year
Language support	C#, C++
nKey (Ticket)	1024 Pages
Automatic upgrade service	SDK is always up to date, plus including new features
Ncode SDK
Premium 
(Optional)
Server plus	xxx GB/ xxx GB/ xxx GB ​​(​To be decided)	Data transfer traffic cost
Language plus	Java/ Linux/ etc.	10,000 USD/ language
nKey (Ticket) plus	Additional order for a customized service	100 USD / 10240 pages (20nKey)
Technical Support	Consultant of developing a customized service	Actual expenses is required (​Business trip fee, ​L​abor fee per hour or etc.)


If you want to try this, please let us know the following information.

Account ID (required)
Password (required)
Company name (required)
Extra information for account (simple text information. if you are going to create multiple accounts)
Application names (required)
Extra information for application (simple text information. if you are going to create multiple applications)

**Comment by hrhwang** [comment]
This is the NCode pricing policy.

![ncode_policy](https://cloud.githubusercontent.com/assets/24997185/26298939/fcccff64-3f13-11e7-85be-1cfc660da7e9.png)



If you want to try this, please let us know the following information.

Account ID (required)
Password (required)
Company name (required)
Extra information for account (simple text information. if you are going to create multiple accounts)
Application names (required)
Extra information for application (simple text information. if you are going to create multiple applications)

If you have any further questions, please contact hjhwang@neolab.net

**Comment by smartrxhub** [comment]
We have email  hjhwang@neolab.net   our company detail , Please let us know when can be account ready?

**Comment by JulieHwang** [comment]
@smartrxhub I sent a reply to you by an email. Thank you.

**Comment by smartrxhub** [comment]
Julie - I have replied your email , Please can you get back to us.
