### ISSUE TITLE
BadImageFormatException when starting sample app

### ISSUE THREAD

**Issue by inkmike** [NeoSmartpen/NcodeSDK#3]
I'm trying to run the sample app in cs_adobe_pdf_sample. The solution actually doesn't compile when opened - the references to NeoLABNcodeSDK, Newtonsoft.Json and PDFLibAgent are all broken. I manually fix the references by pointing them to the dlls in cs_adobe_pdf_sample\dll. Then, when running the sample app, the following exception occurs on app entry (Program.cs line 82):

_An unhandled exception of type 'System.BadImageFormatException' occurred in sampleApp(Ncode_cs_adobe).exe_

_Additional information: Could not load file or assembly 'NeoLABNcodeSDK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format._

What is the solution to this?

**Comment by hrhwang** [comment]
This is a personally answered question, but I leave it for people who need it.
This library works fine in a 64-bit environment. Fixing the build environment with x64 solves this problem.

**Comment by DivyaPam** [comment]
I am getting error in 64-bit only. which is of Datalogics.PDFL like (Could not load file or assembly 'Datalogics.PDFL, Version=2.2.15760.15011, Culture=neutral, PublicKeyToken=ec84850197728341)

What is the solution?
