### ISSUE TITLE
Adobe PDF issue

### ISSUE THREAD

**Issue by DivyaPam** [NeoSmartpen/NcodeSDK#4]
Hello,

I am getting error (Could not load file or assembly 'Datalogics.PDFL, Version=2.2.15760.15011, Culture=neutral, PublicKeyToken=ec84850197728341'). Can you suggest me where I am doing a mistake?

Thank You.

**Comment by hrhwang** [comment]
Hello,
I have uploded new dll files match with Datalogics 15.0.4 version.
If you are using newest Datalogics library, you can use the dll file in Datalogics.PDFL.2.2.15743.15043 folder.
Try to replace PdfLibAgent,dll file and build your project.
If it occurs same error, please let me know the Datalogics library version you are using.
I'll build a new dll, and upload it.

**Comment by DivyaPam** [comment]
Hello,

I am getting still the same error. Screenshot attached. I have used all the
latest DLLs which are then on GitHub.

Thank You. Regards

**Comment by hrhwang** [comment]
Please let me know the Datalogics library file name you are using.
(for example, APDFL15.0.4PlusP3g_Win-x64_LM.exe)

**Comment by DivyaPam** [comment]
APDFL15.0.4PlusP4c_Win-x64_LM.exe

**Comment by hrhwang** [comment]
If the library you are using is trial version, can you deliver me your install file?
I'll build and upload new dll about 15.0.4PlusP4c version.

**Comment by DivyaPam** [comment]
http://www.datalogics.com/pdflibinfo/grzqordg/sgio_zlq64/apdfl_lm.zip

This one is the download link. As I can not attach the file here.

**Comment by hrhwang** [comment]
I have updated new dll.(for APDFL15.0.4PlusP4c)
Please try again.
Thank you.

**Comment by DivyaPam** [comment]
Thanks. It work's fine now.

Now I am getting false in lib.init but that might be due to library key
which I am passing.

**Comment by PriyankGadhiya** [comment]
Could not load file or assembly 'Datalogics.PDFL, Version=2.2.1582.15044, Culture=neutral, PublicKeyToken=ec84850197728341' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
![bug](https://user-images.githubusercontent.com/44332568/47263366-d048cd00-d51d-11e8-86f8-107b71805e2e.PNG)

**Comment by PriyankGadhiya** [comment]
Hello 
I have some question about PDF Control Initialise , i can't do initialise PDF Control .
Can you suggest me how to initialling PDF Control , How to use the libkey ?? @hrhwang 

![capture](https://user-images.githubusercontent.com/44332568/50675871-ee02da00-1016-11e9-914a-21f1b505593f.PNG)

**Comment by hrhwang** [comment]
Are there any version-related errors as mentioned above?
If so, send me the installation file of the Datalogics library you are using.
I will build a new PdfLibAgent.dll and send it to you.
If it is just a lib key problem, it can be found in the sample code provided by Datalogics.

**Comment by PriyankGadhiya** [comment]
ok sir thank you for reply
you can provide the full details of data logic lib key using guide then
send me please...

<https://about.me/priyankgadhiya?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Priyank Gadhiya
about.me/priyankgadhiya
<https://about.me/priyankgadhiya?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
