### ISSUE TITLE
Ncode page information is out of range.

### ISSUE THREAD

**Issue by PriyankGadhiya** [NeoSmartpen/NcodeSDK#7]
Let me ask a question here.
I'd like to clarify for books.

i have to one ticket
I'll be printing 600 pages times in a while then i'll face the Error

![capture](https://user-images.githubusercontent.com/44332568/51227502-a6674100-197a-11e9-9a77-3303193a9d1b.PNG)

How do I print the 600 page for my book? in one time

How to use book wise pages print ?? 
Please someone help me out.
It's very urgent...

**Comment by hrhwang** [comment]
The Ncode SDK uses a ticket to generate an Ncode page.
Tickets have 256 to 512 pages per book, depending on the type.
To print 600 pages at a time, you need to change the book in the middle.

**Comment by PriyankGadhiya** [comment]
Can u describe where book id need to be set ?

Please provide link with NCode SDK Documentation

**Comment by hrhwang** [comment]
It's very simple.
You can find below snippet at sample code.

int ticketIndex = 0;
int bookOffset = 2;
int pageOffset = 15;
CNcodeSDK.TicketInfo pageInfo = sdk.SetStartPageByOffset(tickets[ticketIndex], bookOffset, pageOffset);

Select ticket and set book and page offset.
If page number is over, add 1 to book offset and set page offset 0.

Are you using your own app key? Or using just free sample key?

**Comment by PriyankGadhiya** [comment]
Thank you so much for reply 
i'm using own app key ..

**Comment by PriyankGadhiya** [comment]
int ticketIndex = 0;
int bookOffset = 3;
int pageOffset = 0;
CNcodeSDK.TicketInfo pageInfo = sdk.SetStartPageByOffset(tickets[ticketIndex], bookOffset, pageOffset);

i'm also set PageStart number 
tickets[i].pageStart = 606;

I'm currently printing page no is 606 
When I set pagestart greater then 512 up then 
Same Previous Error  (Ncode page information is out of range).

Now suggest me what to do next ?

**Comment by hrhwang** [comment]
Please let me know your email address.
I'll check your code more detail.

**Comment by smartrxhub** [comment]
Hi Priyank
I can help to resolve this problem , Please provide skype /Whatapps details.
thanksPraful

    On Wednesday, January 16, 2019, 10:11:45 p.m. EST, Priyank Gadhiya <notifications@github.com> wrote:  
 
 
int ticketIndex = 0;
int bookOffset = 3;
int pageOffset = 0;
CNcodeSDK.TicketInfo pageInfo = sdk.SetStartPageByOffset(tickets[ticketIndex], bookOffset, pageOffset);

I'm currently printing page no is 606
Same Previous Error (Ncode page information is out of range).

Now suggest me what to do next ?
